# Generated by Django 3.2.8 on 2021-11-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='Product',
            new_name='product',
        ),
    ]
